### ISSUE TITLE
bug sanefalcon 

### ISSUE THREAD

**Issue by dprat** [uca-mdlab/sanefalcon#6]
```
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    merge_all(fm)
  File "/home/mdlab/sanefalcon/merge.py", line 162, in merge_all
    merge_subs(merge_subs_files, fm.trainfolder)
  File "/home/mdlab/sanefalcon/merge.py", line 117, in merge_subs
    launch_multithreads(runs, name='merge_subs')
  File "/home/mdlab/sanefalcon/merge.py", line 39, in launch_multithreads
    _ = job.result()
  File "/home/mdlab/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/mdlab/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/mdlab/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mdlab/sanefalcon/merge.py", line 80, in _merge
    data = read_all_files(files)
  File "/home/mdlab/sanefalcon/merge.py", line 59, in read_all_files
    data.extend([int(line.strip()) for line in open(f, 'r')])
FileNotFoundError: [Errno 2] No such file or directory: '5'
```

**Comment by marcomilanesio** [comment]
Closed 62e985ead11f26ca006688816bd02602d3b4b163
